### ISSUE TITLE
[CP scoping] Graph for KPI comparison is incorrect 

### ISSUE THREAD

**Issue by MildaMa** [Leadera/ecoman_repo#113]
![file-page1](https://cloud.githubusercontent.com/assets/9460158/5934427/9de5dcac-a6cf-11e4-8150-2f7eaf108003.png)

**Comment by tcgumus** [comment]
![image](https://cloud.githubusercontent.com/assets/2714346/6002496/876dfe42-aafc-11e4-929e-1f1b12426db5.png)
   
Problem solved.
- KPI error value deleted from KPI calculation page since it has no
value and causes confusion.
- KPI graph are recoded. Colors are changed based on condition is good or
bad. Calculations are changed.
