### ISSUE TITLE
Functionnalities for modification of project members and profile on a specific project page

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#123]
Page of interest: http://88.249.18.205:8090/ecoman/project/17

On the project page, 

-	Could there be a button “add consultant to project” that will allow to define other consultant that will be able to modify the project. This button will give access to the list of consultant that are registered in the ECOMAN platform. If the consultant is not registered in the ECOMAN platform, there should be a possibility to invite him to create a user account on ECOMAN and join the project (e.g. through an email address)

-	Could there be a button “assign company to project”? This button will give access to the list of company that are registered in the ECOMAN platform. If the company is not registered in the ECOMAN platform, there should be a direct link allowing to either
o	create a new company (the company will automatically be integrated to the specific project)
o	invite the company to create a user account on ECOMAN and join the project (e.g. through an email address and the sending of a generic email to invite to join the platform)

-	Could there be a button “Update project info” for the modification of any other information related to the projects (status,…)

**Comment by tcgumus** [comment]
You can add consultants to a project by clicking project info and then by selecting consultants in "Assign Consultant" field. Invitation can be implemented later 1.0 since we should plan a use-case.
    
You can assign new companies to a project now. Before making changes in project pages we should clear our minds i guess. For example, what will happen when one user clicks create a new company in project pages? Is user already registered? Will we make a control for login? What will happen if a user cancels company creation? You said earlier user should only see the projects they can edit so i did the changes. If a user is wants to create a company he can by clicking in create company button in companies section and then he can select the project (if they can edit) they can add their company to it. If they cant edit it, they wont be able to see the project.   
    
There is already a button for project data update and it is called "Update project info". 
![image](https://cloud.githubusercontent.com/assets/2714346/5999181/028b5c70-aad8-11e4-84ee-a3743861ddf9.png)

**Comment by gmassard** [comment]
Ok, now I understand how to add a company to one project. It is not very user friendly but it work.

When a new user will register on the platform, the program should ask if this is company or a consultant.

what will happen when one user clicks create a new company in project pages?
User will only have access to the project page if they are consultant. One company that register from its own initiative should be suggested to join on existing project, or to create one.

Is user already registered?
User should be ask to register while joining on project. Then he create its company profile while accepted in one project.

 Will we make a control for login? 
Yes

What will happen if a user cancels company creation? 
Which user type? A consultant or a company? A consultant can reject a company demand to join a project.

**Comment by gmassard** [comment]
Dear Tuna,

I think this issue is still important for user rights and rules. Did you had time to look at it?

**Comment by emilyvuylsteke** [comment]
This should be discussed with Guillaume, to verify if it should be solved for version 1 or not
