### ISSUE TITLE
Button for "dataset management" missing for the pouly company

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#124]
Page of interest: http://88.249.18.205:8090/ecoman/company/77

The page of this company does not show the “dataset management” button. This company has been created on the 30th of jan. If I go to another company page (eg this one http://88.249.18.205:8090/ecoman/company/65, created about 10 days ago) the “dataset management” button appears. Could this be fixed?

**Comment by tcgumus** [comment]
It is not a bug, it is a feature :) You can only edit the companies you are a consultant of or you created. Pouly company created by guillaume and has no project. Since it has no project, you are not a consultant of this company like others. 
       
You should create a project or update an already registered project and **add Pouly company to the project you are consultant of**. So you can edit the company info and dataset. 
   
On the other hand Givaudan company created by you so you have already permission for editing data of this company.

**Comment by gmassard** [comment]
Ok, but how do I add Pouly to an existing project? I should be obliged to create a project for each new company?
This development is still not mature. I understand your explanation, but navigability and company profile, edition, assignment to project is not clear.
I'm reopening the issue

**Comment by tcgumus** [comment]
You can add a new company by clicking update project button and select the company you want to add  in the "Assign Company" field. You can select more than one company at the same time. Also you can select more than consultant as well. You don't need to create a new project for every company. A project can include all companies in the system you selected. There is no limit for company and consultant numbers in project.

Please test it and respond. Thank you.

![image](https://cloud.githubusercontent.com/assets/2714346/6108949/eecf90e0-b07f-11e4-8d33-c03caa9725a4.png)

**Comment by gmassard** [comment]
Ok, now I understand! Sorry.
Not very intuitive, but it works!
Thank you Tuna
