### ISSUE TITLE
Projects page: alphabetic order and map for localization

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#127]
Page of interest: http://88.249.18.205:8090/ecoman/projects

Could the projects be listed in alphabetic order?
Could there be a map localizing the project of this list? (Related issue n°125 for the localization of project)

Remark: the project page should be adapted to the “project approach”. Thus, only project related to one user account should be displayed on the list and on the map.

**Comment by emilyvuylsteke** [comment]
Thank you for solving the alphabetic order issue. This works fine!
Concerning the map issue: on the “my projects”, the map appears fine. What about the “all projects” map? There is a window for such a map but it does not appear. (see printscreen)
Also, can the zoom level be define for the whole world? 
![image](https://cloud.githubusercontent.com/assets/10558805/7453906/5ff843e0-f26e-11e4-898e-6904f79d3366.png)

**Comment by emilyvuylsteke** [comment]
Can you discuss with Guillaume if this is a refinement or if it should be solved for version 1? Thanks in advance.

**Comment by gmassard** [comment]
Hi Zeynel,
Thank you for the excellent job on many issues. To finalize version one, I would like to assure that maps display correctly. Can you please check the map on the all project page?
The map does not display. Can you fixed it? This is very important for demos...
Then, can you fix the zone level at the "world" scale, so that user will se the entire planet when arriving on this page, then they can zoom on continents or countries..

**Comment by corner82** [comment]
Hi Guillaume,
You know I did not code that part, but when I made a debug I found a solution I think, You may test the issue, 
P.S.the map places its zoom level according to markers automatically

**Comment by gmassard** [comment]
Hi Zeynel,
Thank you! Yes, now it works! Great!
About your PS, I know currently the map places its zoom automatically. But it would be better to see the all world when you get to the page, and then zoom to the continent or country we want to look at.
Possible?

**Comment by corner82** [comment]
Hi Guillaume,
I'm sure it is possible, but you know cause I did not make the coding that map, I don't want to involve a code part too much which I don't know much, I tried to find the bug and fix it, but further development Tuna can help you I think,
P.S. I don't want to make a mistake and break code before demo, Mr. Tuna can help you for that issue, will be more suitable I assume

**Comment by gmassard** [comment]
Thank you Zeynel.
Tuna, can you take over this issue?

**Comment by tcgumus** [comment]
Hello Guillaume, 
Map now works like, it is automatically zooming to show all the project in one picture. For example, if there is a project in USA. You will recognise that the map will show also USA (from usa to turkey) when you first opened the page. Another example, if you go to my projects page you will see map zoom has changed to a different level that contains all your projects. If you had project only in turkey, you will see only turkey on the map when you first opened it. You can always zoom in and out with clicking +- buttons or using mouse wheel. 

![screen shot 2015-05-11 at 15 10 14](https://cloud.githubusercontent.com/assets/2714346/7564705/1ec96cd0-f7f2-11e4-8bc9-6626750e40d2.png)

Also for the note for future :) the problem caused because of the some projects didn't have any lang and long values in the database. I have filled their map information and the other pages also started working right now.

**Comment by tcgumus** [comment]
![screen shot 2015-05-11 at 15 49 54](https://cloud.githubusercontent.com/assets/2714346/7566118/6bab0ccc-f7f5-11e4-8d0e-f63e9154d6a1.png)

All companies page with a company in USA.

**Comment by gmassard** [comment]
Hi Tuna,
When I get on this page, I see rather the following image. Then the zoom level is not very nice as dots are nearly on the image margin... So my suggestion was to set up the zoom scale for all maps at the "world" level and then the user zoom.
Do you understand my suggestion?
![untitled](https://cloud.githubusercontent.com/assets/9587966/7566984/809e4810-f7fa-11e4-922b-d9e3b52658b4.png)

**Comment by tcgumus** [comment]
It will be look like this; 
![screen shot 2015-05-13 at 12 32 08](https://cloud.githubusercontent.com/assets/2714346/7608707/3099b5e8-f96c-11e4-99b7-a5fdc792dda2.png)

Do you approve?
Best,
Tuna

**Comment by gmassard** [comment]
Hi Tuna,

Yes, I think ti's the best solution to start at the world scale...
Thank you

Best

Guillaume

**Comment by gmassard** [comment]
Ca we do the same for the "My projects" page?

**Comment by tcgumus** [comment]
I have added same function to my projects page and all companies page

**Comment by tcgumus** [comment]
Please test it and close it. Thank you.

**Comment by tcgumus** [comment]
we have tested this page. closing it now.
