### ISSUE TITLE
IS scenario: data display for a manual IS scenario

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#510]
- Bug : the details of the potential that appears in the table 3 is not correct. Indeed, one of the line should inform the other company. here the two lines inform on the details of the flow of the same company (see printscreen)
![screen shot 2015-09-21 at 19 40 24](https://cloud.githubusercontent.com/assets/10558805/9999977/abfaebd2-6099-11e5-80df-c0723a92bb8d.png)

- Same request as in issue n° 509, for step 4: In the line of the potential in table 2, the name of the 2 flows should display. It should displays like this: company/quantity/flow/company/quantity/flow/...

**Comment by corner82** [comment]
This is totally scenario related issue, You probably made related ıs scenario on 'manual IS page',
cause on automated IS you caanot match 'holcim' and 'abb' companies on 'cuivre' flow,

so on details you cannot see 'holcim' because you dont have 'cuivre' flow related with company 'holcim' on  database,
but you can make a match manually (because consultant can have the freedom to do that as decided earlier),
so this is not system bug, this consultant missuse of the tool, thanks...

**Comment by gmassard** [comment]
Hi Zeynel,

The exemple Emily gave is a manual IS detection. So yes, we selected manually two different flows from two different companies. The issue title mention "manual IS". 
But when you see the result on the IS scenario page, only the name of one flow appears. So the scenario page needs to be adapted for manual IS detection, in order to have the two different name of the flow appearing on the "IS project details" table.
Can you please work on it?

**Comment by corner82** [comment]
issue closed, further modifications can be tracked #516
