### ISSUE TITLE
"erase", "edit profile" and "dataset management" button next to company name

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#96]
Page of interest: 
http://88.249.18.205:8090/ecoman/company

Can you please add next to each company name:
- an “erase” button ?
- an "edit profile" button?
- an "dataset management" button?

**Comment by corner82** [comment]
Mr.Tuna has been coded related code blocks, so I assign him this issue, he later can mark milestone...

**Comment by emilyvuylsteke** [comment]
This issue has not been solved yet. Thanks in advance for taking this issue into account.

**Comment by tcgumus** [comment]
Hello,
If you have permission on the company. you should be able to see dataset management and edit profile button next to it? Can you share a screenshot. 
Thanks

**Comment by emilyvuylsteke** [comment]
Here is a screenshot.

![screen shot 2015-05-01 at 13 23 43](https://cloud.githubusercontent.com/assets/10558805/7429659/89e0607c-f005-11e4-87b8-84e7b8e15ab5.png)

**Comment by tcgumus** [comment]
ok. now i get it :+1: but i will add the button if you have permission to edit the company. ok?

**Comment by emilyvuylsteke** [comment]
Yes this seems good. Thanks in advance!

**Comment by emilyvuylsteke** [comment]
Let me know when I can test this issue again

**Comment by tcgumus** [comment]
Now you can get directly to the dataset management or edit page of the companies in the all companies, my companies and project companies pages. If you have a permission you will see the buttons next to the names of the companies (if you are logged in of course). 

![screen shot 2015-06-09 at 15 02 07](https://cloud.githubusercontent.com/assets/2714346/8058293/b9538772-0eb8-11e5-9a40-a4d858b0b897.png)

"DELETE" button has not been added yet since we don't have a feature like that but we can close this issue for now.
